services:
  web:
    build: ./docker
    user: "$UID:$GID"
    volumes:
      - ./web:/var/www/html
    ports:
      - 80:80
      - 8080:8080
    environment:
      - USER_ID=${UID}
      - GROUP_ID=${GID}

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_files:/var/lib/mysql

volumes:
  db_files: