services:
  web:
    build: ./docker
    user: "$UID:$GID"
    volumes:
      - ./web:/var/www/html
    ports:
      - 80:80
      - 8080:8080
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
